// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD70i0FvJuO6uf7FjpfrcihQGCUZk-0r1A',
    appId: '1:305373806422:web:af34b8ad1202a8a4efe0f7',
    messagingSenderId: '305373806422',
    projectId: 'crypto-wallet-45662',
    authDomain: 'crypto-wallet-45662.firebaseapp.com',
    storageBucket: 'crypto-wallet-45662.firebasestorage.app',
    measurementId: 'G-33FFV0GS1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeAySyYcxVys6tgF9xv5PGQAMjRBGrjvk',
    appId: '1:305373806422:android:f7051740621213cbefe0f7',
    messagingSenderId: '305373806422',
    projectId: 'crypto-wallet-45662',
    storageBucket: 'crypto-wallet-45662.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvZVBZ7ghiV3GFGjcNCgHofZebc5kHJQ0',
    appId: '1:305373806422:ios:5b405dda52e321bbefe0f7',
    messagingSenderId: '305373806422',
    projectId: 'crypto-wallet-45662',
    storageBucket: 'crypto-wallet-45662.firebasestorage.app',
    iosBundleId: 'com.example.cex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvZVBZ7ghiV3GFGjcNCgHofZebc5kHJQ0',
    appId: '1:305373806422:ios:5b405dda52e321bbefe0f7',
    messagingSenderId: '305373806422',
    projectId: 'crypto-wallet-45662',
    storageBucket: 'crypto-wallet-45662.firebasestorage.app',
    iosBundleId: 'com.example.cex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD70i0FvJuO6uf7FjpfrcihQGCUZk-0r1A',
    appId: '1:305373806422:web:9d79e9223b4ffb83efe0f7',
    messagingSenderId: '305373806422',
    projectId: 'crypto-wallet-45662',
    authDomain: 'crypto-wallet-45662.firebaseapp.com',
    storageBucket: 'crypto-wallet-45662.firebasestorage.app',
    measurementId: 'G-S8WDLYXVN4',
  );
}
